### ISSUE TITLE
Xian_example1.driver not writing Xian_hs.bil

### ISSUE THREAD

**Issue by BenjiDa** [LSDtopotools/LSDTopoTools_ChiMudd2014#2]
Per instructions Im running chi_mapping_tool.exe with the Xian_example1.driver, it works great but does not write a hillshade even with "write hillshade: true" set. This wouldn't be an issue but it seems that python visualization scripts i.e. "ChiMappingExamples.py" are dependent on Xian_hs. See error below:

 `Exception: [Errno 2] No such file or directory: '/my/path/VagrantBoxes/LSDTopoTools/Topographic_projects/LSDTT_chi_examples/Xian_hs.bil'`

**Comment by BenjiDa** [comment]
Something similar happens when running `MW.PrintChannels(DataDirectory,Base_file)` from `ChiMappingExamples.py`

Error: `IOError: File /my/path/VagrantBoxes/LSDTopoTools/Topographic_projects/LSDTT_chi_examples/Xian_chi_data_map.csv does not exist`

I cannot figure out how to write `Xian_chi_data_map.csv` by changing the parameter file (`Xian_example1.driver`).

**Comment by BenjiDa** [comment]
Regarding hillshade error,  `write_hillshade: true` produces a hillshade image. However this image has many "holes", see fig. 

![screen shot 2017-08-04 at 2 16 44 pm](https://user-images.githubusercontent.com/18178879/28987507-587436de-7920-11e7-8371-ae29466dfeaf.png)

**Comment by simon-m-mudd** [comment]
Problem 1 is that Martin changed the the write hillshade flag to "write_hillshade" rather than "write hillshade" (i.e. it now has an underscore) to be consistent with other write commands. I didn't update the docs. I'll do that soonish. 

To print the chi data maps, you need to set "print_chi_data_maps: true"

I'm afraid our development branch and python branches have got a bit ahead of the documentation! I'll try to rectify next week. 

For the holes: I'm not sure what is happening there. Is that an image from QGIS? QGIS has an annoying feature that it plots from the 1-99% values so you sometimes get missing values. The only other thing I can think of is that the DEM has some nodata.
